"use client";
/* eslint-disable @next/next/no-img-element -- local data URLs cannot use the Next image optimizer */

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ToolDefinition } from "../lib/tools";
import { parsePageSelection, parseBaseInteger, readPreference, writePreference, readList, randomIndex, generatePassword } from "../lib/tool-utils";

function ActionButton({ children, onClick, secondary = false, disabled = false }: { children: React.ReactNode; onClick: () => void; secondary?: boolean; disabled?: boolean }) {
  return <button className={`tool-button ${secondary ? "secondary" : ""}`} onClick={onClick} disabled={disabled}>{children}</button>;
}

function CopyButton({ value }: { value: string }) {
  const [status, setStatus] = useState("Copy");
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
  async function copy() {
    try { await navigator.clipboard.writeText(value); setStatus("Copied ✓"); }
    catch { setStatus("Select text to copy"); }
    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(() => setStatus("Copy"), 2000);
  }
  return <button className="mini-button" onClick={copy} disabled={!value} aria-live="polite">{status}</button>;
}

function TextArea({ value, onChange, placeholder, label }: { value: string; onChange: (value: string) => void; placeholder: string; label: string }) {
  return <textarea className="tool-textarea" aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} spellCheck={false} />;
}

function JsonTool() {
  const [input, setInput] = useState('{"project":"Toolstack","private":true,"tools":19}');
  const [output, setOutput] = useState('{\n  "project": "Toolstack",\n  "private": true,\n  "tools": 19\n}'); const [error, setError] = useState("");
  function transform(minify = false) { try { const parsed = JSON.parse(input); setOutput(JSON.stringify(parsed, null, minify ? 0 : 2)); setError(""); } catch (e) { setOutput(""); setError(e instanceof Error ? e.message : "Invalid JSON"); } }
  return <div className="tool-panels"><section><PanelHead title="Input" action={<button className="mini-button" onClick={() => { setInput(""); setOutput(""); setError(""); }}>Clear</button>} /><TextArea value={input} onChange={setInput} label="JSON input" placeholder="Paste JSON here…" /><div className="tool-actions"><ActionButton onClick={() => transform()}>Format JSON</ActionButton><ActionButton secondary onClick={() => transform(true)}>Minify</ActionButton></div>{error && <p className="tool-error" role="alert">● {error}</p>}</section><section><PanelHead title="Result" action={<CopyButton value={output} />} /><pre className="code-output">{output || "Your formatted JSON will appear here."}</pre></section></div>;
}

function PanelHead({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="panel-head"><h2>{title}</h2>{action}</div>; }

function CodecTool({ kind }: { kind: "base64" | "url" }) {
  const [input, setInput] = useState(""); const [output, setOutput] = useState(""); const [error, setError] = useState("");
  function run(mode: "encode" | "decode") { try { let result = ""; if (kind === "url") result = mode === "encode" ? encodeURIComponent(input) : decodeURIComponent(input); else if (mode === "encode") { const bytes = new TextEncoder().encode(input); let binary = ""; bytes.forEach(b => binary += String.fromCharCode(b)); result = btoa(binary); } else result = new TextDecoder().decode(Uint8Array.from(atob(input), c => c.charCodeAt(0))); setOutput(result); setError(""); } catch { setError(`That doesn't look like valid ${kind === "url" ? "encoded URL content" : "Base64"}.`); setOutput(""); } }
  return <div className="tool-panels"><section><PanelHead title="Input" /><TextArea value={input} onChange={setInput} label={`${kind} input`} placeholder="Type or paste your content…" /><div className="tool-actions"><ActionButton onClick={() => run("encode")}>Encode</ActionButton><ActionButton secondary onClick={() => run("decode")}>Decode</ActionButton></div>{error && <p className="tool-error" role="alert">● {error}</p>}</section><section><PanelHead title="Result" action={<CopyButton value={output} />} /><pre className="code-output wrap">{output || "Your result will appear here."}</pre></section></div>;
}

function UuidTool() {
  const [count, setCount] = useState(5); const [values, setValues] = useState<string[]>([]);
  function generate() { setValues(Array.from({ length: count }, () => crypto.randomUUID())); }
  const output = values.join("\n");
  return <section className="single-panel"><PanelHead title="Secure UUID v4 batch" action={<CopyButton value={output} />} /><label className="range-label">How many? <strong>{count}</strong></label><input className="range" type="range" min="1" max="50" value={count} onChange={e => setCount(Number(e.target.value))} /><pre className="code-output uuid-list">{output || "Click generate to create secure UUIDs."}</pre><ActionButton onClick={generate}>Generate new UUIDs</ActionButton></section>;
}

function HashTool() {
  const [input, setInput] = useState(""); const [algorithm, setAlgorithm] = useState("SHA-256"); const [output, setOutput] = useState("");
  async function generate() { const hash = await crypto.subtle.digest(algorithm, new TextEncoder().encode(input)); setOutput(Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, "0")).join("")); }
  return <div className="tool-panels"><section><PanelHead title="Text to hash" /><TextArea value={input} onChange={setInput} label="Text to hash" placeholder="Enter sensitive text—it never leaves your device…" /><div className="inline-controls"><select aria-label="Hash algorithm" value={algorithm} onChange={e => { setAlgorithm(e.target.value); setOutput(""); }}><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select><ActionButton onClick={generate}>Generate hash</ActionButton></div></section><section><PanelHead title={algorithm} action={<CopyButton value={output} />} /><pre className="code-output wrap">{output || "Your cryptographic hash will appear here."}</pre></section></div>;
}

const WORDS = ["amber", "bridge", "cactus", "drift", "ember", "forest", "galaxy", "harbor", "indigo", "jungle", "kiwi", "lantern", "meadow", "nectar", "orbit", "pebble", "quartz", "river", "signal", "timber"];
function PasswordTool() {
  const [length, setLength] = useState(20); const [wordCount, setWordCount] = useState(16);
  const [upper, setUpper] = useState(true); const [numbers, setNumbers] = useState(true); const [symbols, setSymbols] = useState(true);
  const [passphrase, setPassphrase] = useState(false); const [password, setPassword] = useState(""); const [detail, setDetail] = useState("");
  function generate() {
    if (passphrase) {
      setPassword(Array.from({ length: wordCount }, () => WORDS[randomIndex(WORDS.length)]).join("-"));
      setDetail(`${wordCount} random words · ${Math.floor(wordCount * Math.log2(WORDS.length))} bits of entropy`);
    } else {
      const groups = ["abcdefghijklmnopqrstuvwxyz", ...(upper ? ["ABCDEFGHIJKLMNOPQRSTUVWXYZ"] : []), ...(numbers ? ["0123456789"] : []), ...(symbols ? ["!@#$%^&*_-+="] : [])];
      setPassword(generatePassword(length, groups));
      setDetail(`${length} characters · includes every selected character type`);
    }
  }
  return <section className="single-panel password-panel"><PanelHead title="Password generator" action={<CopyButton value={password} />} /><div className="password-output">{password || "Choose your settings, then generate a password."}</div>{detail && <p className="process-message" role="status">{detail}</p>}<label className="range-label">{passphrase ? "Word count" : "Length"} <strong>{passphrase ? wordCount : length}</strong></label><input aria-label={passphrase ? "Word count" : "Password length"} className="range" type="range" min={passphrase ? 16 : 8} max={passphrase ? 24 : 64} value={passphrase ? wordCount : length} onChange={e => passphrase ? setWordCount(Number(e.target.value)) : setLength(Number(e.target.value))} /><div className="check-grid">{!passphrase && <><Toggle label="Uppercase" checked={upper} set={setUpper} /><Toggle label="Numbers" checked={numbers} set={setNumbers} /><Toggle label="Symbols" checked={symbols} set={setSymbols} /></>}<Toggle label="Passphrase mode" checked={passphrase} set={setPassphrase} /></div><p className="file-info">Uses your browser’s cryptographic random generator.{passphrase ? " The compact 20-word dictionary requires longer phrases. Use character mode for a shorter password." : " Lowercase letters are always included."}</p><ActionButton onClick={generate}>Generate {passphrase ? "passphrase" : "password"}</ActionButton></section>;
}

function Toggle({ label, checked, set }: { label: string; checked: boolean; set: (v: boolean) => void }) { return <label className="toggle"><input type="checkbox" checked={checked} onChange={e => set(e.target.checked)} /><span />{label}</label>; }

function WordCounter() {
  const [text, setText] = useState(""); const stats = useMemo(() => { const trimmed = text.trim(); const words = trimmed ? trimmed.split(/\s+/).length : 0; const sentences = trimmed ? (trimmed.match(/[.!?]+(?=\s|$)/g)?.length || 1) : 0; return { words, chars: text.length, noSpaces: text.replace(/\s/g, "").length, sentences, paragraphs: trimmed ? trimmed.split(/\n\s*\n/).length : 0, read: Math.max(0, Math.ceil(words / 225)) }; }, [text]);
  return <section className="single-panel"><div className="stats-grid">{[["Words", stats.words], ["Characters", stats.chars], ["No spaces", stats.noSpaces], ["Sentences", stats.sentences], ["Paragraphs", stats.paragraphs], ["Read time", `${stats.read} min`]].map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><TextArea value={text} onChange={setText} label="Text to analyze" placeholder="Start typing or paste your text here…" /></section>;
}

function splitWords(text: string) { return text.trim().replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[_-]+/g, " ").split(/\s+/).filter(Boolean); }
function CaseConverter() {
  const [text, setText] = useState(""); const words = splitWords(text); const lower = words.map(w => w.toLowerCase()); const outputs: [string, string][] = [["UPPERCASE", text.toUpperCase()], ["lowercase", text.toLowerCase()], ["Title Case", lower.map(w => w[0]?.toUpperCase() + w.slice(1)).join(" ")], ["camelCase", lower.map((w,i) => i ? w[0]?.toUpperCase()+w.slice(1) : w).join("")], ["PascalCase", lower.map(w => w[0]?.toUpperCase()+w.slice(1)).join("")], ["snake_case", lower.join("_")], ["kebab-case", lower.join("-")], ["CONSTANT_CASE", lower.join("_").toUpperCase()]];
  return <div className="tool-panels"><section><PanelHead title="Your text" /><TextArea value={text} onChange={setText} label="Text to convert" placeholder="Type something to transform…" /></section><section><PanelHead title="Conversions" /><div className="conversion-list">{outputs.map(([label,value]) => <div key={label}><span>{label}</span><code>{value || "—"}</code><CopyButton value={value} /></div>)}</div></section></div>;
}

const LOREM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
function LoremTool() { const [count, setCount] = useState(3); const [output, setOutput] = useState(Array(3).fill(LOREM).join("\n\n")); function generate(){ setOutput(Array.from({length: count}, (_,i) => i ? LOREM : LOREM.replace("Lorem ipsum", "Toolstack ipsum")).join("\n\n")); } return <section className="single-panel"><PanelHead title="Generated copy" action={<CopyButton value={output} />} /><div className="inline-controls"><label>Paragraphs <input className="number-input" type="number" min="1" max="20" value={count} onChange={e => setCount(Math.min(20, Math.max(1, Number(e.target.value))))} /></label><ActionButton onClick={generate}>Generate</ActionButton></div><pre className="code-output wrap tall">{output}</pre></section>; }

function RegexTool() { const [pattern,setPattern]=useState("\\b(tool|tools)\\b"); const [flags,setFlags]=useState("gi"); const [text,setText]=useState("Toolstack puts useful tools in one fast, private place."); let matches: RegExpMatchArray[]=[]; let error=""; try { matches=Array.from(text.matchAll(new RegExp(pattern, flags.includes("g") ? flags : flags+"g"))); } catch(e){ error=e instanceof Error?e.message:"Invalid expression"; } return <div className="tool-panels"><section><PanelHead title="Expression" /><div className="regex-input"><span>/</span><input value={pattern} onChange={e=>setPattern(e.target.value)} aria-label="Regular expression"/><span>/</span><input className="flags" value={flags} onChange={e=>setFlags(e.target.value)} aria-label="Regular expression flags"/></div><PanelHead title="Test text" /><TextArea value={text} onChange={setText} label="Regex test text" placeholder="Text to search…" />{error&&<p className="tool-error" role="alert">{error}</p>}</section><section><PanelHead title={`${matches.length} match${matches.length===1?"":"es"}`} /><div className="match-list">{matches.map((m,i)=><div key={`${m.index}-${i}`}><strong>{m[0]}</strong><span>index {m.index}</span></div>)}{!matches.length&&!error&&<p>No matches yet.</p>}</div></section></div>; }

function hexToRgb(hex: string) { let clean=hex.replace("#",""); if(clean.length===3) clean=clean.split("").map(c=>c+c).join(""); if(!/^[0-9a-f]{6}$/i.test(clean)) return null; const n=parseInt(clean,16); return {r:(n>>16)&255,g:(n>>8)&255,b:n&255}; }
function rgbToHsl(r:number,g:number,b:number){ r/=255;g/=255;b/=255; const max=Math.max(r,g,b),min=Math.min(r,g,b); let h=0,s=0; const l=(max+min)/2; if(max!==min){ const d=max-min;s=l>.5?d/(2-max-min):d/(max+min); if(max===r)h=(g-b)/d+(g<b?6:0);else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h/=6;} return {h:Math.round(h*360),s:Math.round(s*100),l:Math.round(l*100)}; }
function ColorTool(){ const [hex,setHex]=useState("#b7f34a"); const rgb=hexToRgb(hex); const hsl=rgb?rgbToHsl(rgb.r,rgb.g,rgb.b):null; const values=rgb&&hsl?[["HEX",hex.toUpperCase()],["RGB",`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`],["HSL",`hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)`]]:[]; return <div className="tool-panels color-tool"><section><div className="color-preview" style={{background:rgb?hex:"#222"}}><input type="color" value={rgb?`#${[rgb.r,rgb.g,rgb.b].map(n=>n.toString(16).padStart(2,"0")).join("")}`:"#000000"} onChange={e=>setHex(e.target.value)} aria-label="Pick a color"/></div><label className="field-label">HEX value<input value={hex} onChange={e=>setHex(e.target.value)} /></label>{!rgb&&<p className="tool-error" role="alert">Enter a valid 3 or 6 digit HEX color.</p>}</section><section><PanelHead title="Color values" /><div className="conversion-list">{values.map(([label,value])=><div key={label}><span>{label}</span><code>{value}</code><CopyButton value={value}/></div>)}</div></section></div>; }

function TimestampTool(){
  const [timestamp,setTimestamp]=useState("0"); const [unit,setUnit]=useState("seconds");
  const numeric=Number(timestamp); const date=new Date(numeric*(unit==="seconds"?1000:1));
  const valid=/^[+-]?\d+$/.test(timestamp.trim()) && Number.isSafeInteger(numeric) && !Number.isNaN(date.getTime());
  const now=()=>setTimestamp((unit==="seconds"?Math.floor(Date.now()/1000):Date.now()).toString());
  return <div className="tool-panels"><section><PanelHead title="Unix timestamp" /><label className="field-label">Unit<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="seconds">Seconds</option><option value="milliseconds">Milliseconds</option></select></label><label className="field-label">Timestamp<input value={timestamp} onChange={e=>setTimestamp(e.target.value)} placeholder="For example, 0 or -86400"/></label><ActionButton onClick={now}>Use current time</ActionButton></section><section><PanelHead title="Human-readable date" action={<CopyButton value={valid?date.toISOString():""}/>} />{valid?<div className="date-output"><strong suppressHydrationWarning>{date.toLocaleString()}</strong><span>{date.toISOString()}</span><span>{date.toUTCString()}</span><span>Unix seconds: {Math.floor(date.getTime()/1000)}</span></div>:<p className="tool-error" role="alert">Enter a whole timestamp in the selected unit.</p>}</section></div>;
}

function NumberBaseTool(){ const [value,setValue]=useState("255"); const [base,setBase]=useState(10); const number=parseBaseInteger(value,base); const outputs=number!==null?[["Binary",number.toString(2)],["Octal",number.toString(8)],["Decimal",number.toString(10)],["Hexadecimal",number.toString(16).toUpperCase()]]:[]; return <div className="tool-panels"><section><PanelHead title="Input number"/><label className="field-label">Source base<select value={base} onChange={e=>setBase(Number(e.target.value))}><option value="2">Binary</option><option value="8">Octal</option><option value="10">Decimal</option><option value="16">Hexadecimal</option></select></label><label className="field-label">Value<input value={value} onChange={e=>setValue(e.target.value.trim())}/></label>{number===null&&<p className="tool-error" role="alert">That value is not valid in base {base}.</p>}</section><section><PanelHead title="Conversions"/><div className="conversion-list">{outputs.map(([label,result])=><div key={label}><span>{label}</span><code>{result}</code><CopyButton value={result}/></div>)}</div></section></div>; }

function ImageCompressor(){ const [source,setSource]=useState<string>(""); const [result,setResult]=useState<string>(""); const [quality,setQuality]=useState(.78); const [info,setInfo]=useState(""); const originalSize=useRef(0); function choose(file?:File){ if(!file)return; if(!file.type.startsWith("image/")){setInfo("Please choose an image file.");return;} originalSize.current=file.size; const reader=new FileReader();reader.onload=()=>{setSource(String(reader.result));setResult("");setInfo(`${file.name} · ${(file.size/1024).toFixed(1)} KB`)};reader.readAsDataURL(file); } function compress(){ if(!source)return; const img=new Image();img.onload=()=>{const max=1800;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d")?.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL("image/webp",quality);setResult(data);const bytes=Math.round((data.length-data.indexOf(",")-1)*.75);setInfo(`${canvas.width}×${canvas.height} · ${(bytes/1024).toFixed(1)} KB · ${Math.max(0,Math.round((1-bytes/originalSize.current)*100))}% smaller`);};img.src=source;} function download(){const a=document.createElement("a");a.href=result;a.download="toolstack-compressed.webp";a.click();} return <section className="single-panel image-panel"><label className="drop-zone"><input type="file" accept="image/*" onChange={e=>choose(e.target.files?.[0])}/>{source?<img src={result||source} alt="Image preview"/>:<><strong>Choose an image to compress</strong><span>JPG, PNG or WebP · processed locally</span></>}</label>{info&&<p className="file-info">{info}</p>}<label className="range-label">Quality <strong>{Math.round(quality*100)}%</strong></label><input className="range" type="range" min="20" max="95" value={quality*100} onChange={e=>setQuality(Number(e.target.value)/100)}/><div className="tool-actions"><ActionButton onClick={compress} disabled={!source}>Compress image</ActionButton>{result&&<ActionButton secondary onClick={download}>Download WebP</ActionButton>}</div></section>; }

function downloadBlob(blob: Blob, name: string) { const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
function readDataUrl(file: File) { return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);}); }

function ImageConverter(){
  const [source,setSource]=useState(""); const [fileName,setFileName]=useState("image"); const [format,setFormat]=useState("image/jpeg"); const [quality,setQuality]=useState(.9); const [result,setResult]=useState(""); const [info,setInfo]=useState("");
  async function choose(file?:File){if(!file)return;if(!file.type.startsWith("image/")){setInfo("Choose a PNG, JPG or WebP image.");return;}setSource(await readDataUrl(file));setFileName(file.name.replace(/\.[^.]+$/,"")||"image");setResult("");setInfo(`${file.name} · ${(file.size/1024).toFixed(1)} KB`);}
  function convert(){if(!source)return;const image=new Image();image.onload=()=>{const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext("2d");if(!context)return;if(format==="image/jpeg"){context.fillStyle="#ffffff";context.fillRect(0,0,canvas.width,canvas.height);}context.drawImage(image,0,0);const data=canvas.toDataURL(format,quality);setResult(data);setInfo(`${canvas.width}×${canvas.height} · ${format.replace("image/","").toUpperCase()} · ${(Math.round((data.length-data.indexOf(",")-1)*.75)/1024).toFixed(1)} KB`);};image.src=source;}
  const extension=format==="image/jpeg"?"jpg":format.split("/")[1];
  return <section className="single-panel image-panel"><label className="drop-zone compact"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choose(e.target.files?.[0])}/>{source?<img src={result||source} alt="Conversion preview"/>:<><strong>Choose an image to convert</strong><span>PNG, JPG and WebP supported</span></>}</label><div className="format-grid"><label className="field-label">Output format<select value={format} onChange={e=>{setFormat(e.target.value);setResult("");}}><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label><label className="range-label stacked">Quality <strong>{Math.round(quality*100)}%</strong><input className="range" type="range" min="20" max="100" value={quality*100} onChange={e=>setQuality(Number(e.target.value)/100)}/></label></div>{info&&<p className="file-info">{info}</p>}<div className="tool-actions"><ActionButton onClick={convert} disabled={!source}>Convert to {extension.toUpperCase()}</ActionButton>{result&&<ActionButton secondary onClick={()=>downloadBlob(fetchDataBlob(result),`${fileName}.${extension}`)}>Download {extension.toUpperCase()}</ActionButton>}</div></section>;
}

function fetchDataBlob(dataUrl:string){const [header,data]=dataUrl.split(",");const mime=header.match(/:(.*?);/)?.[1]||"application/octet-stream";const binary=atob(data);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime});}

function FileQueue({files,setFiles}: {files:File[];setFiles:(files:File[])=>void}){
  function move(index:number,direction:number){const target=index+direction;if(target<0||target>=files.length)return;const next=[...files];[next[index],next[target]]=[next[target],next[index]];setFiles(next);}
  return <div className="file-queue">{files.map((file,index)=><div key={`${file.name}-${file.lastModified}-${index}`}><span className="file-number">{index+1}</span><span><strong>{file.name}</strong><small>{(file.size/1024).toFixed(1)} KB</small></span><div><button onClick={()=>move(index,-1)} disabled={index===0} aria-label={`Move ${file.name} up`}>↑</button><button onClick={()=>move(index,1)} disabled={index===files.length-1} aria-label={`Move ${file.name} down`}>↓</button><button onClick={()=>setFiles(files.filter((_,itemIndex)=>itemIndex!==index))} aria-label={`Remove ${file.name}`}>×</button></div></div>)}</div>;
}

function ImagesToPdf(){
  const [files,setFiles]=useState<File[]>([]);const [working,setWorking]=useState(false);const [message,setMessage]=useState("");
  async function create(){if(!files.length)return;setWorking(true);setMessage("Building your PDF…");try{const {PDFDocument}=await import("pdf-lib");const pdf=await PDFDocument.create();for(const file of files){const bytes=await file.arrayBuffer();const image=file.type==="image/png"?await pdf.embedPng(bytes):await pdf.embedJpg(bytes);const maxWidth=595,maxHeight=842,scale=Math.min(maxWidth/image.width,maxHeight/image.height,1);const width=image.width*scale,height=image.height*scale;const page=pdf.addPage([Math.max(width,1),Math.max(height,1)]);page.drawImage(image,{x:0,y:0,width,height});}const output=await pdf.save();downloadBlob(new Blob([new Uint8Array(output)],{type:"application/pdf"}),"toolstack-images.pdf");setMessage(`Created ${files.length}-page PDF successfully.`);}catch{setMessage("One of the images could not be converted. Use PNG or JPG files.");}finally{setWorking(false);}}
  return <section className="single-panel"><label className="file-picker"><input type="file" multiple accept="image/png,image/jpeg" onChange={e=>setFiles([...files,...Array.from(e.target.files||[])])}/><strong>Add PNG or JPG images</strong><span>Choose multiple files, then arrange their page order</span></label><FileQueue files={files} setFiles={setFiles}/>{message&&<p className="process-message" role="status">{message}</p>}<div className="tool-actions"><ActionButton onClick={create} disabled={!files.length||working}>{working?"Creating PDF…":"Create PDF"}</ActionButton>{files.length>0&&<ActionButton secondary onClick={()=>{setFiles([]);setMessage("");}}>Clear all</ActionButton>}</div></section>;
}

function PdfMerger(){
  const [files,setFiles]=useState<File[]>([]);const [working,setWorking]=useState(false);const [message,setMessage]=useState("");
  async function merge(){if(files.length<2)return;setWorking(true);setMessage("Combining documents…");try{const {PDFDocument}=await import("pdf-lib");const merged=await PDFDocument.create();let pages=0;for(const file of files){const source=await PDFDocument.load(await file.arrayBuffer());const copied=await merged.copyPages(source,source.getPageIndices());copied.forEach(page=>merged.addPage(page));pages+=copied.length;}const output=await merged.save();downloadBlob(new Blob([new Uint8Array(output)],{type:"application/pdf"}),"toolstack-merged.pdf");setMessage(`Merged ${files.length} files and ${pages} pages successfully.`);}catch{setMessage("A PDF could not be read. Password-protected PDFs are not supported.");}finally{setWorking(false);}}
  return <section className="single-panel"><label className="file-picker"><input type="file" multiple accept="application/pdf" onChange={e=>setFiles([...files,...Array.from(e.target.files||[])])}/><strong>Add PDF documents</strong><span>Select two or more files and arrange their order</span></label><FileQueue files={files} setFiles={setFiles}/>{message&&<p className="process-message" role="status">{message}</p>}<div className="tool-actions"><ActionButton onClick={merge} disabled={files.length<2||working}>{working?"Merging PDFs…":"Merge PDFs"}</ActionButton>{files.length>0&&<ActionButton secondary onClick={()=>{setFiles([]);setMessage("");}}>Clear all</ActionButton>}</div></section>;
}

function PdfExtractor(){
  const [file,setFile]=useState<File|null>(null);const [selection,setSelection]=useState("1");const [pageCount,setPageCount]=useState(0);const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
  async function choose(next?:File){if(!next)return;setFile(next);setMessage("Reading PDF…");try{const {PDFDocument}=await import("pdf-lib");const pdf=await PDFDocument.load(await next.arrayBuffer());setPageCount(pdf.getPageCount());setSelection(`1-${Math.min(3,pdf.getPageCount())}`);setMessage(`${pdf.getPageCount()} pages detected.`);}catch{setFile(null);setPageCount(0);setMessage("This PDF could not be read.");}}
  async function extract(){if(!file)return;setWorking(true);try{const {PDFDocument}=await import("pdf-lib");const source=await PDFDocument.load(await file.arrayBuffer());const indices=parsePageSelection(selection,source.getPageCount());if(!indices.length)throw new Error();const output=await PDFDocument.create();const pages=await output.copyPages(source,indices);pages.forEach(page=>output.addPage(page));const bytes=await output.save();downloadBlob(new Blob([new Uint8Array(bytes)],{type:"application/pdf"}),"toolstack-extracted-pages.pdf");setMessage(`Extracted ${indices.length} page${indices.length===1?"":"s"}.`);}catch{setMessage(`Use pages between 1 and ${pageCount}, for example 1-3,5.`);}finally{setWorking(false);}}
  return <section className="single-panel"><label className="file-picker"><input type="file" accept="application/pdf" onChange={e=>choose(e.target.files?.[0])}/><strong>{file?file.name:"Choose a PDF"}</strong><span>{file?`${(file.size/1024).toFixed(1)} KB`:"Select the document you want to split"}</span></label>{file&&<label className="field-label">Pages to extract<input value={selection} onChange={e=>setSelection(e.target.value)} placeholder="1-3,5,8"/></label>}{message&&<p className="process-message" role="status">{message}</p>}<ActionButton onClick={extract} disabled={!file||working}>{working?"Extracting…":"Extract selected pages"}</ActionButton></section>;
}

function BackgroundRemover(){
  const [source,setSource]=useState("");const [result,setResult]=useState("");const [threshold,setThreshold]=useState(42);const [feather,setFeather]=useState(28);const [status,setStatus]=useState("");
  async function choose(file?:File){if(!file)return;setSource(await readDataUrl(file));setResult("");setStatus(`${file.name} ready. Best results use a plain background.`);}
  function remove(){if(!source)return;setStatus("Removing background…");const image=new Image();image.onload=()=>{const max=2200,scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)return;context.drawImage(image,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height);const data=pixels.data;const samples=[[0,0],[canvas.width-1,0],[0,canvas.height-1],[canvas.width-1,canvas.height-1]];let red=0,green=0,blue=0;for(const [x,y] of samples){const index=(y*canvas.width+x)*4;red+=data[index];green+=data[index+1];blue+=data[index+2];}red/=4;green/=4;blue/=4;for(let index=0;index<data.length;index+=4){const distance=Math.hypot(data[index]-red,data[index+1]-green,data[index+2]-blue);if(distance<=threshold)data[index+3]=0;else if(distance<threshold+feather)data[index+3]=Math.round(255*(distance-threshold)/Math.max(feather,1));}context.putImageData(pixels,0,0);setResult(canvas.toDataURL("image/png"));setStatus(`${canvas.width}×${canvas.height} transparent PNG ready.`);};image.src=source;}
  return <section className="single-panel image-panel"><label className="drop-zone checker compact"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choose(e.target.files?.[0])}/>{source?<img src={result||source} alt="Background removal preview"/>:<><strong>Choose an image</strong><span>For best results use a plain, evenly lit background</span></>}</label><div className="format-grid"><label className="range-label stacked">Removal strength <strong>{threshold}</strong><input className="range" type="range" min="8" max="120" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><label className="range-label stacked">Edge softness <strong>{feather}</strong><input className="range" type="range" min="0" max="80" value={feather} onChange={e=>setFeather(Number(e.target.value))}/></label></div>{status&&<p className="process-message" role="status">{status}</p>}<div className="tool-actions"><ActionButton onClick={remove} disabled={!source}>Remove background</ActionButton>{result&&<ActionButton secondary onClick={()=>downloadBlob(fetchDataBlob(result),"toolstack-no-background.png")}>Download PNG</ActionButton>}</div></section>;
}

function ToolBody({ slug }: { slug: string }) { switch(slug){case"json-formatter":return <JsonTool/>;case"base64":return <CodecTool kind="base64"/>;case"url-codec":return <CodecTool kind="url"/>;case"uuid-generator":return <UuidTool/>;case"hash-generator":return <HashTool/>;case"password-generator":return <PasswordTool/>;case"word-counter":return <WordCounter/>;case"case-converter":return <CaseConverter/>;case"lorem-ipsum":return <LoremTool/>;case"regex-tester":return <RegexTool/>;case"color-converter":return <ColorTool/>;case"timestamp-converter":return <TimestampTool/>;case"number-base":return <NumberBaseTool/>;case"image-compressor":return <ImageCompressor/>;case"image-converter":return <ImageConverter/>;case"background-remover":return <BackgroundRemover/>;case"images-to-pdf":return <ImagesToPdf/>;case"pdf-merger":return <PdfMerger/>;case"pdf-extractor":return <PdfExtractor/>;default:return null;} }

export default function ToolWorkspace({ tool }: { tool: ToolDefinition }) {
  const [dark,setDark]=useState(true);
  useEffect(()=>{ const theme=readPreference("toolstack:theme"); const next=theme?theme==="dark":true;queueMicrotask(()=>setDark(next));document.documentElement.dataset.theme=next?"dark":"light"; const recent=readList("toolstack:recent");writePreference("toolstack:recent",JSON.stringify([tool.slug,...recent.filter(s=>s!==tool.slug)].slice(0,8)));},[tool.slug]);
  function toggleTheme(){const next=!dark;setDark(next);document.documentElement.dataset.theme=next?"dark":"light";writePreference("toolstack:theme",next?"dark":"light");}
  return <main className="workspace-page"><header className="nav shell"><Link className="brand" href="/"><span className="brand-mark">T</span><span>toolstack</span></Link><div className="nav-actions"><Link className="back-link" href="/">← All tools</Link><button className="icon-button" onClick={toggleTheme} aria-label="Toggle theme">{dark?"☼":"☾"}</button></div></header><div className="workspace shell"><div className="workspace-heading"><div className={`tool-icon large accent-bg-${tool.accent}`}>{tool.icon}</div><div><span className="tool-category">{tool.category} tool</span><h1>{tool.name}</h1><p>{tool.description}</p></div><div className="local-chip"><span>●</span> Secure workspace</div></div><ToolBody key={tool.slug} slug={tool.slug}/><div className="privacy-note"><strong>Your files stay private.</strong> Files and text are processed in your browser and never uploaded to our servers.</div></div><footer className="footer shell"><Link className="brand" href="/"><span className="brand-mark">T</span><span>toolstack</span></Link><p>Useful things, thoughtfully made.</p><div><Link href="/">All tools</Link><span>© 2026</span></div></footer></main>;
}
