"use client";
/* eslint-disable @next/next/no-img-element -- local data URLs cannot use the Next image optimizer */

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ToolDefinition } from "../lib/tools";

function ActionButton({ children, onClick, secondary = false, disabled = false }: { children: React.ReactNode; onClick: () => void; secondary?: boolean; disabled?: boolean }) {
  return <button className={`tool-button ${secondary ? "secondary" : ""}`} onClick={onClick} disabled={disabled}>{children}</button>;
}

function CopyButton({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  async function copy() { await navigator.clipboard.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 1400); }
  return <button className="mini-button" onClick={copy} disabled={!value}>{copied ? "Copied ✓" : "Copy"}</button>;
}

function TextArea({ value, onChange, placeholder, label }: { value: string; onChange: (value: string) => void; placeholder: string; label: string }) {
  return <textarea className="tool-textarea" aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} spellCheck={false} />;
}

function JsonTool() {
  const [input, setInput] = useState('{"project":"Toolstack","private":true,"tools":14}');
  const [output, setOutput] = useState('{\n  "project": "Toolstack",\n  "private": true,\n  "tools": 14\n}'); const [error, setError] = useState("");
  function transform(minify = false) { try { const parsed = JSON.parse(input); setOutput(JSON.stringify(parsed, null, minify ? 0 : 2)); setError(""); } catch (e) { setOutput(""); setError(e instanceof Error ? e.message : "Invalid JSON"); } }
  return <div className="tool-panels"><section><PanelHead title="Input" action={<button className="mini-button" onClick={() => setInput("")}>Clear</button>} /><TextArea value={input} onChange={setInput} label="JSON input" placeholder="Paste JSON here…" /><div className="tool-actions"><ActionButton onClick={() => transform()}>Format JSON</ActionButton><ActionButton secondary onClick={() => transform(true)}>Minify</ActionButton></div>{error && <p className="tool-error">● {error}</p>}</section><section><PanelHead title="Result" action={<CopyButton value={output} />} /><pre className="code-output">{output || "Your formatted JSON will appear here."}</pre></section></div>;
}

function PanelHead({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="panel-head"><h2>{title}</h2>{action}</div>; }

function CodecTool({ kind }: { kind: "base64" | "url" }) {
  const [input, setInput] = useState(""); const [output, setOutput] = useState(""); const [error, setError] = useState("");
  function run(mode: "encode" | "decode") { try { let result = ""; if (kind === "url") result = mode === "encode" ? encodeURIComponent(input) : decodeURIComponent(input); else if (mode === "encode") { const bytes = new TextEncoder().encode(input); let binary = ""; bytes.forEach(b => binary += String.fromCharCode(b)); result = btoa(binary); } else result = new TextDecoder().decode(Uint8Array.from(atob(input), c => c.charCodeAt(0))); setOutput(result); setError(""); } catch { setError(`That doesn't look like valid ${kind === "url" ? "encoded URL content" : "Base64"}.`); setOutput(""); } }
  return <div className="tool-panels"><section><PanelHead title="Input" /><TextArea value={input} onChange={setInput} label={`${kind} input`} placeholder="Type or paste your content…" /><div className="tool-actions"><ActionButton onClick={() => run("encode")}>Encode</ActionButton><ActionButton secondary onClick={() => run("decode")}>Decode</ActionButton></div>{error && <p className="tool-error">● {error}</p>}</section><section><PanelHead title="Result" action={<CopyButton value={output} />} /><pre className="code-output wrap">{output || "Your result will appear here."}</pre></section></div>;
}

function UuidTool() {
  const [count, setCount] = useState(5); const [values, setValues] = useState<string[]>(["Click generate to create secure UUIDs."]);
  function generate() { setValues(Array.from({ length: count }, () => crypto.randomUUID())); }
  const output = values.join("\n");
  return <section className="single-panel"><PanelHead title="Secure UUID v4 batch" action={<CopyButton value={output} />} /><label className="range-label">How many? <strong>{count}</strong></label><input className="range" type="range" min="1" max="50" value={count} onChange={e => setCount(Number(e.target.value))} /><pre className="code-output uuid-list">{output}</pre><ActionButton onClick={generate}>Generate new UUIDs</ActionButton></section>;
}

function HashTool() {
  const [input, setInput] = useState(""); const [algorithm, setAlgorithm] = useState("SHA-256"); const [output, setOutput] = useState("");
  async function generate() { const hash = await crypto.subtle.digest(algorithm, new TextEncoder().encode(input)); setOutput(Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, "0")).join("")); }
  return <div className="tool-panels"><section><PanelHead title="Text to hash" /><TextArea value={input} onChange={setInput} label="Text to hash" placeholder="Enter sensitive text—it never leaves your device…" /><div className="inline-controls"><select value={algorithm} onChange={e => setAlgorithm(e.target.value)}><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select><ActionButton onClick={generate}>Generate hash</ActionButton></div></section><section><PanelHead title={algorithm} action={<CopyButton value={output} />} /><pre className="code-output wrap">{output || "Your cryptographic hash will appear here."}</pre></section></div>;
}

const WORDS = ["amber", "bridge", "cactus", "drift", "ember", "forest", "galaxy", "harbor", "indigo", "jungle", "kiwi", "lantern", "meadow", "nectar", "orbit", "pebble", "quartz", "river", "signal", "timber"];
function PasswordTool() {
  const [length, setLength] = useState(20); const [upper, setUpper] = useState(true); const [numbers, setNumbers] = useState(true); const [symbols, setSymbols] = useState(true); const [passphrase, setPassphrase] = useState(false); const [password, setPassword] = useState("Click regenerate to create a password");
  function generate() { if (passphrase) { setPassword(Array.from({ length: Math.max(3, Math.round(length / 5)) }, () => WORDS[crypto.getRandomValues(new Uint32Array(1))[0] % WORDS.length]).join("-")); return; } const chars = "abcdefghijklmnopqrstuvwxyz" + (upper ? "ABCDEFGHIJKLMNOPQRSTUVWXYZ" : "") + (numbers ? "0123456789" : "") + (symbols ? "!@#$%^&*_-+=" : ""); const random = crypto.getRandomValues(new Uint32Array(length)); setPassword(Array.from(random, n => chars[n % chars.length]).join("")); }
  const score = Math.min(100, length * 3 + (upper ? 12 : 0) + (numbers ? 12 : 0) + (symbols ? 18 : 0));
  return <section className="single-panel password-panel"><PanelHead title="Your secure password" action={<CopyButton value={password} />} /><div className="password-output">{password}</div><div className="strength"><span style={{ width: `${score}%` }} /><small>{score > 75 ? "Excellent" : score > 50 ? "Strong" : "Fair"}</small></div><label className="range-label">Length <strong>{length}</strong></label><input className="range" type="range" min="8" max="64" value={length} onChange={e => setLength(Number(e.target.value))} /><div className="check-grid"><Toggle label="Uppercase" checked={upper} set={setUpper} /><Toggle label="Numbers" checked={numbers} set={setNumbers} /><Toggle label="Symbols" checked={symbols} set={setSymbols} /><Toggle label="Passphrase mode" checked={passphrase} set={setPassphrase} /></div><ActionButton onClick={generate}>Regenerate password</ActionButton></section>;
}

function Toggle({ label, checked, set }: { label: string; checked: boolean; set: (v: boolean) => void }) { return <label className="toggle"><input type="checkbox" checked={checked} onChange={e => set(e.target.checked)} /><span />{label}</label>; }

function WordCounter() {
  const [text, setText] = useState(""); const stats = useMemo(() => { const trimmed = text.trim(); const words = trimmed ? trimmed.split(/\s+/).length : 0; const sentences = trimmed ? (trimmed.match(/[.!?]+(?=\s|$)/g)?.length || 1) : 0; return { words, chars: text.length, noSpaces: text.replace(/\s/g, "").length, sentences, paragraphs: trimmed ? trimmed.split(/\n\s*\n/).length : 0, read: Math.max(0, Math.ceil(words / 225)) }; }, [text]);
  return <section className="single-panel"><div className="stats-grid">{[["Words", stats.words], ["Characters", stats.chars], ["No spaces", stats.noSpaces], ["Sentences", stats.sentences], ["Paragraphs", stats.paragraphs], ["Read time", `${stats.read} min`]].map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><TextArea value={text} onChange={setText} label="Text to analyze" placeholder="Start typing or paste your text here…" /></section>;
}

function splitWords(text: string) { return text.trim().replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[_-]+/g, " ").split(/\s+/).filter(Boolean); }
function CaseConverter() {
  const [text, setText] = useState(""); const words = splitWords(text); const lower = words.map(w => w.toLowerCase()); const outputs: [string, string][] = [["UPPERCASE", text.toUpperCase()], ["lowercase", text.toLowerCase()], ["Title Case", lower.map(w => w[0]?.toUpperCase() + w.slice(1)).join(" ")], ["camelCase", lower.map((w,i) => i ? w[0]?.toUpperCase()+w.slice(1) : w).join("")], ["PascalCase", lower.map(w => w[0]?.toUpperCase()+w.slice(1)).join("")], ["snake_case", lower.join("_")], ["kebab-case", lower.join("-")], ["CONSTANT_CASE", lower.join("_").toUpperCase()]];
  return <div className="tool-panels"><section><PanelHead title="Your text" /><TextArea value={text} onChange={setText} label="Text to convert" placeholder="Type something to transform…" /></section><section><PanelHead title="Conversions" /><div className="conversion-list">{outputs.map(([label,value]) => <div key={label}><span>{label}</span><code>{value || "—"}</code><CopyButton value={value} /></div>)}</div></section></div>;
}

const LOREM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
function LoremTool() { const [count, setCount] = useState(3); const [output, setOutput] = useState(Array(3).fill(LOREM).join("\n\n")); function generate(){ setOutput(Array.from({length: count}, (_,i) => i ? LOREM : LOREM.replace("Lorem ipsum", "Toolstack ipsum")).join("\n\n")); } return <section className="single-panel"><PanelHead title="Generated copy" action={<CopyButton value={output} />} /><div className="inline-controls"><label>Paragraphs <input className="number-input" type="number" min="1" max="20" value={count} onChange={e => setCount(Math.min(20, Math.max(1, Number(e.target.value))))} /></label><ActionButton onClick={generate}>Generate</ActionButton></div><pre className="code-output wrap tall">{output}</pre></section>; }

function RegexTool() { const [pattern,setPattern]=useState("\\b(tool|tools)\\b"); const [flags,setFlags]=useState("gi"); const [text,setText]=useState("Toolstack puts useful tools in one fast, private place."); let matches: RegExpMatchArray[]=[]; let error=""; try { matches=Array.from(text.matchAll(new RegExp(pattern, flags.includes("g") ? flags : flags+"g"))); } catch(e){ error=e instanceof Error?e.message:"Invalid expression"; } return <div className="tool-panels"><section><PanelHead title="Expression" /><div className="regex-input"><span>/</span><input value={pattern} onChange={e=>setPattern(e.target.value)} aria-label="Regular expression"/><span>/</span><input className="flags" value={flags} onChange={e=>setFlags(e.target.value)} aria-label="Regular expression flags"/></div><PanelHead title="Test text" /><TextArea value={text} onChange={setText} label="Regex test text" placeholder="Text to search…" />{error&&<p className="tool-error">{error}</p>}</section><section><PanelHead title={`${matches.length} match${matches.length===1?"":"es"}`} /><div className="match-list">{matches.map((m,i)=><div key={`${m.index}-${i}`}><strong>{m[0]}</strong><span>index {m.index}</span></div>)}{!matches.length&&!error&&<p>No matches yet.</p>}</div></section></div>; }

function hexToRgb(hex: string) { let clean=hex.replace("#",""); if(clean.length===3) clean=clean.split("").map(c=>c+c).join(""); if(!/^[0-9a-f]{6}$/i.test(clean)) return null; const n=parseInt(clean,16); return {r:(n>>16)&255,g:(n>>8)&255,b:n&255}; }
function rgbToHsl(r:number,g:number,b:number){ r/=255;g/=255;b/=255; const max=Math.max(r,g,b),min=Math.min(r,g,b); let h=0,s=0; const l=(max+min)/2; if(max!==min){ const d=max-min;s=l>.5?d/(2-max-min):d/(max+min); if(max===r)h=(g-b)/d+(g<b?6:0);else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h/=6;} return {h:Math.round(h*360),s:Math.round(s*100),l:Math.round(l*100)}; }
function ColorTool(){ const [hex,setHex]=useState("#b7f34a"); const rgb=hexToRgb(hex); const hsl=rgb?rgbToHsl(rgb.r,rgb.g,rgb.b):null; const values=rgb&&hsl?[["HEX",hex.toUpperCase()],["RGB",`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`],["HSL",`hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)`]]:[]; return <div className="tool-panels color-tool"><section><div className="color-preview" style={{background:rgb?hex:"#222"}}><input type="color" value={rgb?hex:"#000000"} onChange={e=>setHex(e.target.value)} aria-label="Pick a color"/></div><label className="field-label">HEX value<input value={hex} onChange={e=>setHex(e.target.value)} /></label>{!rgb&&<p className="tool-error">Enter a valid 3 or 6 digit HEX color.</p>}</section><section><PanelHead title="Color values" /><div className="conversion-list">{values.map(([label,value])=><div key={label}><span>{label}</span><code>{value}</code><CopyButton value={value}/></div>)}</div></section></div>; }

function TimestampTool(){ const [timestamp,setTimestamp]=useState(()=>Math.floor(Date.now()/1000).toString()); const date=new Date(Number(timestamp)*(timestamp.length<=10?1000:1)); const valid=!Number.isNaN(date.getTime()); const now=()=>setTimestamp(Math.floor(Date.now()/1000).toString()); return <div className="tool-panels"><section><PanelHead title="Unix timestamp" /><label className="field-label">Seconds or milliseconds<input value={timestamp} onChange={e=>setTimestamp(e.target.value.replace(/\D/g,""))}/></label><ActionButton onClick={now}>Use current time</ActionButton></section><section><PanelHead title="Human-readable date" action={<CopyButton value={valid?date.toISOString():""}/>} />{valid?<div className="date-output"><strong>{date.toLocaleString()}</strong><span>{date.toISOString()}</span><span>{date.toUTCString()}</span><span>Unix seconds: {Math.floor(date.getTime()/1000)}</span></div>:<p className="tool-error">Enter a valid timestamp.</p>}</section></div>; }

function NumberBaseTool(){ const [value,setValue]=useState("255"); const [base,setBase]=useState(10); let number:bigint|null=null; try{ number=BigInt(base===10?value:base===16?`0x${value}`:base===8?`0o${value}`:`0b${value}`);}catch{} const outputs=number?[["Binary",number.toString(2)],["Octal",number.toString(8)],["Decimal",number.toString(10)],["Hexadecimal",number.toString(16).toUpperCase()]]:[]; return <div className="tool-panels"><section><PanelHead title="Input number"/><label className="field-label">Source base<select value={base} onChange={e=>setBase(Number(e.target.value))}><option value="2">Binary</option><option value="8">Octal</option><option value="10">Decimal</option><option value="16">Hexadecimal</option></select></label><label className="field-label">Value<input value={value} onChange={e=>setValue(e.target.value.trim())}/></label>{!number&&<p className="tool-error">That value is not valid in base {base}.</p>}</section><section><PanelHead title="Conversions"/><div className="conversion-list">{outputs.map(([label,result])=><div key={label}><span>{label}</span><code>{result}</code><CopyButton value={result}/></div>)}</div></section></div>; }

function ImageCompressor(){ const [source,setSource]=useState<string>(""); const [result,setResult]=useState<string>(""); const [quality,setQuality]=useState(.78); const [info,setInfo]=useState(""); const originalSize=useRef(0); function choose(file?:File){ if(!file)return; if(!file.type.startsWith("image/")){setInfo("Please choose an image file.");return;} originalSize.current=file.size; const reader=new FileReader();reader.onload=()=>{setSource(String(reader.result));setResult("");setInfo(`${file.name} · ${(file.size/1024).toFixed(1)} KB`)};reader.readAsDataURL(file); } function compress(){ if(!source)return; const img=new Image();img.onload=()=>{const max=1800;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d")?.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL("image/webp",quality);setResult(data);const bytes=Math.round((data.length-data.indexOf(",")-1)*.75);setInfo(`${canvas.width}×${canvas.height} · ${(bytes/1024).toFixed(1)} KB · ${Math.max(0,Math.round((1-bytes/originalSize.current)*100))}% smaller`);};img.src=source;} function download(){const a=document.createElement("a");a.href=result;a.download="toolstack-compressed.webp";a.click();} return <section className="single-panel image-panel"><label className="drop-zone"><input type="file" accept="image/*" onChange={e=>choose(e.target.files?.[0])}/>{source?<img src={result||source} alt="Image preview"/>:<><strong>Drop an image or click to browse</strong><span>JPG, PNG or WebP · processed locally</span></>}</label>{info&&<p className="file-info">{info}</p>}<label className="range-label">Quality <strong>{Math.round(quality*100)}%</strong></label><input className="range" type="range" min="20" max="95" value={quality*100} onChange={e=>setQuality(Number(e.target.value)/100)}/><div className="tool-actions"><ActionButton onClick={compress} disabled={!source}>Compress image</ActionButton>{result&&<ActionButton secondary onClick={download}>Download WebP</ActionButton>}</div></section>; }

function ToolBody({ slug }: { slug: string }) { switch(slug){case"json-formatter":return <JsonTool/>;case"base64":return <CodecTool kind="base64"/>;case"url-codec":return <CodecTool kind="url"/>;case"uuid-generator":return <UuidTool/>;case"hash-generator":return <HashTool/>;case"password-generator":return <PasswordTool/>;case"word-counter":return <WordCounter/>;case"case-converter":return <CaseConverter/>;case"lorem-ipsum":return <LoremTool/>;case"regex-tester":return <RegexTool/>;case"color-converter":return <ColorTool/>;case"timestamp-converter":return <TimestampTool/>;case"number-base":return <NumberBaseTool/>;case"image-compressor":return <ImageCompressor/>;default:return null;} }

export default function ToolWorkspace({ tool }: { tool: ToolDefinition }) {
  const [dark,setDark]=useState(true);
  useEffect(()=>{ const theme=localStorage.getItem("toolstack:theme"); const next=theme?theme==="dark":true;queueMicrotask(()=>setDark(next));document.documentElement.dataset.theme=next?"dark":"light"; const recent=JSON.parse(localStorage.getItem("toolstack:recent")||"[]") as string[];localStorage.setItem("toolstack:recent",JSON.stringify([tool.slug,...recent.filter(s=>s!==tool.slug)].slice(0,8)));},[tool.slug]);
  function toggleTheme(){const next=!dark;setDark(next);document.documentElement.dataset.theme=next?"dark":"light";localStorage.setItem("toolstack:theme",next?"dark":"light");}
  return <main className="workspace-page"><header className="nav shell"><Link className="brand" href="/"><span className="brand-mark">T</span><span>toolstack</span></Link><div className="nav-actions"><Link className="back-link" href="/">← All tools</Link><button className="icon-button" onClick={toggleTheme} aria-label="Toggle theme">{dark?"☼":"☾"}</button></div></header><div className="workspace shell"><div className="workspace-heading"><div className={`tool-icon large accent-bg-${tool.accent}`}>{tool.icon}</div><div><span className="tool-category">{tool.category} tool</span><h1>{tool.name}</h1><p>{tool.description} Everything is processed on this device.</p></div><div className="local-chip"><span>●</span> Runs locally</div></div><ToolBody slug={tool.slug}/><div className="privacy-note"><strong>Private by default.</strong> Your content is processed in this browser tab and is not stored or uploaded.</div></div><footer className="footer shell"><Link className="brand" href="/"><span className="brand-mark">T</span><span>toolstack</span></Link><p>Useful things, thoughtfully made.</p><div><Link href="/">All tools</Link><span>© 2026</span></div></footer></main>;
}
